### ISSUE TITLE
py-bsddb not available through macport

### ISSUE THREAD

**Issue by gildash2** [jackjack-jj/pywallet#26]
--->  Computing dependencies for python27
--->  Cleaning python27
--->  Computing dependencies for py27-twisted
--->  Cleaning py27-twisted
--->  Computing dependencies for py27-pip
--->  Cleaning py27-pip
Error: Port py-bsddb not found

This is the error when I try running it. Any work around?

**Comment by jackjack-jj** [comment]
Can you try with `py-bsddb3` instead?

**Comment by gildash2** [comment]
**So, that worked but also didn't:**

(base) macbook-pro:Bitcoin michael.waddell$ export PATH=$PATH:/opt/local/bin
(base) macbook-pro:Bitcoin michael.waddell$ sudo port select --set python python27
Selecting 'python27' for 'python' succeeded. 'python27' is now active.
(base) macbook-pro:Bitcoin michael.waddell$ sudo port install python27 py27-twisted py27-pip py-bsddb3 python_select
--->  Computing dependencies for python27
--->  Cleaning python27
--->  Computing dependencies for py27-twisted
--->  Cleaning py27-twisted
--->  Computing dependencies for py27-pip
--->  Cleaning py27-pip
--->  Computing dependencies for py-bsddb3
The following dependencies will be installed: 
 py38-bsddb3
 py38-setuptools
 python38
Continue? [Y/n]: Y
--->  Fetching archive for python38
--->  Attempting to fetch python38-3.8.7_0.darwin_19.x86_64.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/python38
--->  Attempting to fetch python38-3.8.7_0.darwin_19.x86_64.tbz2.rmd160 from https://ywg.ca.packages.macports.org/mirror/macports/packages/python38
--->  Installing python38 @3.8.7_0
--->  Activating python38 @3.8.7_0
--->  Cleaning python38
--->  Fetching archive for py38-setuptools
--->  Attempting to fetch py38-setuptools-51.3.3_0.darwin_19.noarch.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/py38-setuptools
--->  Attempting to fetch py38-setuptools-51.3.3_0.darwin_19.noarch.tbz2.rmd160 from https://ywg.ca.packages.macports.org/mirror/macports/packages/py38-setuptools
--->  Installing py38-setuptools @51.3.3_0
--->  Activating py38-setuptools @51.3.3_0
--->  Cleaning py38-setuptools
--->  Fetching archive for py38-bsddb3
--->  Attempting to fetch py38-bsddb3-6.2.7_0.darwin_19.x86_64.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/py38-bsddb3
--->  Attempting to fetch py38-bsddb3-6.2.7_0.darwin_19.x86_64.tbz2.rmd160 from https://ywg.ca.packages.macports.org/mirror/macports/packages/py38-bsddb3
--->  Installing py38-bsddb3 @6.2.7_0
--->  Activating py38-bsddb3 @6.2.7_0
--->  Cleaning py38-bsddb3
--->  Fetching archive for py-bsddb3
--->  Attempting to fetch py-bsddb3-6.2.7_0.darwin_19.noarch.tbz2 from https://ywg.ca.packages.macports.org/mirror/macports/packages/py-bsddb3
--->  Attempting to fetch py-bsddb3-6.2.7_0.darwin_19.noarch.tbz2.rmd160 from https://ywg.ca.packages.macports.org/mirror/macports/packages/py-bsddb3
--->  Installing py-bsddb3 @6.2.7_0
--->  Activating py-bsddb3 @6.2.7_0
--->  Cleaning py-bsddb3
--->  Cleaning python_select
--->  Updating database of binaries
--->  Scanning binaries for linking errors
--->  No broken files found.
--->  No broken ports found.
--->  Some of the ports you installed have notes:
  python38 has the following notes:
    To make this the default Python or Python 3 (i.e., the version run by the
    'python' or 'python3' commands), run one or both of:
    
        sudo port select --set python python38
        sudo port select --set python3 python38
(base) macbook-pro:Bitcoin michael.waddell$ python pywallet.py
pywallet.py:22: UserWarning: Python 3 support is still experimental, you may encounter bugs
pywallet needs 'bsddb' package to run, please install it
(base) macbook-pro:Bitcoin michael.waddell$ sudo port select --set python3 python38
Selecting 'python38' for 'python3' succeeded. 'python38' is now active.
(base) macbook-pro:Bitcoin michael.waddell$ python3 pywallet.py
pywallet.py:22: UserWarning: Python 3 support is still experimental, you may encounter bugs
pywallet needs 'bsddb' package to run, please install it


**So it went through all the steps it needed to, but still bsddb is not being recognize. I tried activating various environment to no effect**

(base) macbook-pro:Bitcoin michael.waddell$ sudo port select --set python python38
Selecting 'python38' for 'python' succeeded. 'python38' is now active.
(base) macbook-pro:Bitcoin michael.waddell$ python3 pywallet.py
pywallet.py:22: UserWarning: Python 3 support is still experimental, you may encounter bugs
pywallet needs 'bsddb' package to run, please install it
(base) macbook-pro:Bitcoin michael.waddell$ sudo port select --set python python27
Selecting 'python27' for 'python' succeeded. 'python27' is now active.
(base) macbook-pro:Bitcoin michael.waddell$ python3 pywallet.py
pywallet.py:22: UserWarning: Python 3 support is still experimental, you may encounter bugs
pywallet needs 'bsddb' package to run, please install it
(base) macbook-pro:Bitcoin michael.waddell$ python pywallet.py
pywallet.py:22: UserWarning: Python 3 support is still experimental, you may encounter bugs
pywallet needs 'bsddb' package to run, please install it

**Comment by jackjack-jj** [comment]
I didn't expect Python 3.8 to be installed, but I don't get why even Python 3.8 it doesn't find it once it is
Maybe there's a `py2-bsddb3` or a `py27-bsddb3` and you could try to install to test with Python 2.7?
If it doesn't work can you open a Python 3.8, run `from bsddb.db import *` and report here what error you get?
Same for `from bsddb3.db import *`

**Comment by gildash2** [comment]
macbook-pro:Bitcoin michael.waddell$ python

Python 3.8.3 (default, Jul  2 2020, 11:26:31)

[Clang 10.0.0 ] :: Anaconda, Inc. on darwin

Type "help", "copyright", "credits" or "license" for more information.

>>> from bsddb3.db import *

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ModuleNotFoundError: No module named 'bsddb3'

>>> from bsddb.db import *

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

ModuleNotFoundError: No module named 'bsddb'

>>>


And when running from a python 2.7 conda virtual environment I got the same
errors.


It's a hack, but I supposed I could create a virtual box and run this from
a virtual windows os. Still can't understand why this isn't working though.
This bsddb thing seems to be the bane of everyone's existence going back
almost a decade if you google it along with pywallet.

**Comment by gildash2** [comment]
I think this is progress? At least it's recognizing the module in the lib
folder

>>> import bsddb.db

Traceback (most recent call last):

  File "<stdin>", line 1, in <module>

  File "/opt/anaconda3/envs/bitcoin27/lib/python2.7/bsddb/__init__.py",
line 67, in <module>

    import _bsddb

ImportError: No module named _bsddb

**Comment by gildash2** [comment]
I copied the bsddb3.db package into the  lib as well just to see, and this was the error. 

(bitcoin27) macbook-pro:Bitcoin michael.waddell$ python
Python 2.7.18 |Anaconda, Inc.| (default, Apr 23 2020, 17:44:47) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import bsddb3.db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda3/envs/bitcoin27/lib/python2.7/bsddb3/__init__.py", line 49, in <module>
    import _pybsddb
ImportError: No module named _pybsddb

**Comment by truthsmiles** [comment]
@gildash2 I'm having exactly the same trouble you are. On my own I attempted changing "py-bsddb" to "py-bsddb3" and got the same results you did... python 3.8 was installed, pywallet still complained.
Leaving this comment hoping I'll get a notification if it gets resolved! :)

**Comment by gildash2** [comment]
Okay, so this will hopefully help people. To install the bsddb, this is what I did:

brew install berkeley-db@4

BERKELEYDB_DIR=$(brew --prefix berkeley-db@4) pip install scrapy-deltafetch

Then:

python3 pywallet.py 

worked!

**Comment by jonathanstiansen** [comment]
I think it's a issue with macports - you'll see what when it want's to resolve py-bsddb3, it want's to download py39 and use those versions. For me, (on a Mac) I had to just stop using macports all together, use brew to install the Berkley db - and use: `pip install ecdsa`

Then run the script like this: `BERKELEYDB_DIR=$(brew --prefix berkeley-db@4)  python pywallet.py –dumpwallet` which runs the script, which gets me past the other "missing required" issues - but I'm still getting a:

`pywallet % python pywallet.py --dumpwithbalance
WARNING:root:pycrypto or libssl not found, decryption may be slow
A mandatory option is missing`
