### ISSUE TITLE
TypeError: object of type 'filter' has no len()

### ISSUE THREAD

**Issue by AngelTs** [jackjack-jj/pywallet#41]
Traceback (most recent call last):
  File "c:\$ABC$\pywallet.py", line 3785, in <module>
    recoveredKeys=recov(device, passes, size, 10240, options.recov_outputdir)
  File "c:\$ABC$\pywallet.py", line 1847, in recov
    if len(ckeys_not_decrypted)==0:
TypeError: object of type 'filter' has no len()

**Comment by AngelTs** [comment]
I found the error:
Replace original line (#1846) of pywallet.py

ckeys_not_decrypted=filter(lambda x:x[1].privkey==None, ckeys)

WITH

ckeys_not_decrypted=list(filter(lambda x:x[1].privkey==None, ckeys))

**Comment by masievtec** [comment]
> I found the error: Replace original line (#1846) of pywallet.py
> 
> ckeys_not_decrypted=filter(lambda x:x[1].privkey==None, ckeys)
> 
> WITH
> 
> ckeys_not_decrypted=list(filter(lambda x:x[1].privkey==None, ckeys))

**After changing I have an error:**

Traceback (most recent call last):
  File "pywallet.py", line 2551, in update_wallet
    kds.write_string(d['hash'])
  File "pywallet.py", line 2167, in write_string
    self.write(string)
  File "pywallet.py", line 2136, in write
    self.input += bytes
TypeError: can't concat str to bytes
Traceback (most recent call last):
  File "pywallet.py", line 4072, in <module>
    importprivkey(db, sec+'01', "recovered: %s"%sec, None, False)
TypeError: can't concat str to bytes
